### ISSUE TITLE
Does not run on Windows or OSX

### ISSUE THREAD

**Issue by Jerakin** [defold/extension-qrcode#3]
Running the example/this project crashes it on start up.

I highly suspect it is because of this error in `camera-extension`
https://github.com/defold/extension-camera/issues/3 as the first error is `# 0 pc   0x2d52e5fd ServiceManagement _sigtramp+29` - the same as in that issue.

**Comment by britzl** [comment]
The issue with the camera extension has been resolved. Note that the camera extension does not support Windows, Linux or HTML5
