### ISSUE TITLE
Support bundling/building with unsupported platforms

### ISSUE THREAD

**Issue by Jerakin** [defold/extension-qrcode#5]
Even though the project doesn't support a platform it would be nice if it could still make them bundle/build successfully.

**Comment by JCash** [comment]
This extension doesn't have anything platform related, and builds on all platforms.

The example project though, depends on the extension-camera, which had a previous issue.
Please try this example again.

**Comment by Jerakin** [comment]
That's weird. That's not how I tested it (on Windows).

I made a new empty project and added only the camera extension

![2020-07-19 11_53_12-OfflineTest - Defold Editor 2 0](https://user-images.githubusercontent.com/5273682/87872141-7442ff00-c9b6-11ea-811a-993a98e735cf.png)

**Comment by JCash** [comment]
Thanks, it always helps seeing the actual error.
And I was testing HTML5, since that was what being reported earlier :)

Try again now.

**Comment by Jerakin** [comment]
Awesome! Works now 😁 yay
